name: Deploy Quests to Production
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.REMOTE_DEPLOY_KEY }}

    - name: Pull latest changes on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_DEPLOY_USER }}@${{ secrets.THJ_HOST_ADDR }} '
           cd /opt/eqemu/thj-prod/server/quests &&
           git fetch origin &&
           git reset --hard origin/main'

        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_DEPLOY_USER }}@${{ secrets.RET_HOST_ADDR }} '
           cd /opt/eqemu/ret-prod/server/quests &&
           git fetch origin &&
           git reset --hard origin/main'
           
    - name: Notify discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_STATUS: ${{ job.status }}
